DROP TABLE IF EXISTS T_CATEGORY;

CREATE TABLE T_CATEGORY (
       ID INT NOT NULL AUTO_INCREMENT
     , VERSION INT NOT NULL DEFAULT 0
     , CREATE_DATE DATE NOT NULL
     , UPDATE_DATE DATE NOT NULL
     , SORT_ORDER INT NOT NULL DEFAULT 0
     , NAME VARCHAR(60) NOT NULL
     , PRIMARY KEY (ID)
);